name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [tests, lints]
    permissions:
      contents: write
    strategy:
      matrix:
        target:
        - aarch64-unknown-linux-gnu # ARM64 Linux (kernel 4.1, glibc 2.17+)
        - i686-unknown-linux-gnu # 32-bit Linux (kernel 3.2+, glibc 2.17+)
        - x86_64-unknown-linux-gnu # 64-bit Linux (kernel 3.2+, glibc 2.17+)
        - x86_64-apple-darwin # 64-bit macOS (10.7+, Lion+)
        - i686-pc-windows-msvc # 32-bit MSVC (Windows 7+)
        - x86_64-pc-windows-msvc # 64-bit MSVC (Windows 7+)

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          toolchain: stable
          command: build
          args: --release --target=${{ matrix.target }}
          use-cross: ${{ matrix.cross }}

      - name: Generate subject for provenance
        id: hash
        run: |
          set -euo pipefail
          # List the artifacts the provenance will refer to.
          files=$(ls target/release/clockwork*)
          # Generate the subjects (base64 encoded).
          echo "hashes=$(sha256sum $files | base64 -w0)" >> "${GITHUB_OUTPUT}"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'target/release/clockwork*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}